yt_video_link_domain="https://youtube.com"
is_sort="1"
video_pref="720"
audio_pref="bestaudio"
scrape="youtube"
ytdl_path="/usr/bin/yt-dlp"
#show_thumbnails="1"
#async_thumbnails="1"
#skip_thumb_download="1"
#thumbnail_viewer="ueberzug"
#thumbnail_quality="medium"
is_loop="1"
enable_hist="0"
search_again="1"

